{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Location Distribution",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT col_data_parameters_region AS \"region\", COUNT(*) AS \"users\" FROM user_feedback.pd_banana_logs GROUP BY col_data_parameters_region ORDER BY COUNT(*) DESC "
    }
   ]
  },
  {
   "title": "OS Simple",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT \n    CASE\n        WHEN col_data_parameters_operating_system LIKE 'windows%' THEN 'Windows'\n        WHEN col_data_parameters_operating_system LIKE 'macos%' THEN 'Mac OS'\n        ELSE 'Other'\n    END AS operating_system,\n    COUNT(*) AS count\nFROM user_feedback.pd_banana_logs\nGROUP BY operating_system\n\n"
    }
   ]
  },
  {
   "title": "OS Detailed",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT col_data_parameters_operating_system, COUNT(*) FROM user_feedback.pd_banana_logs GROUP BY col_data_parameters_operating_system ORDER BY COUNT(*) DESC "
    }
   ]
  },
  {
   "title": "License Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT col_data_parameters_app, COUNT(*) FROM user_feedback.pd_banana_logs GROUP BY col_data_parameters_app ORDER BY COUNT(*) DESC "
    }
   ]
  },
  {
   "title": "Releases",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT \n    col_data_parameters_version_number, \n    COUNT(*) AS Users\nFROM user_feedback.pd_banana_logs\nGROUP BY col_data_parameters_version_number\nORDER BY \n    CAST(SUBSTRING_INDEX(col_data_parameters_version_number, '.', 1) AS UNSIGNED) ASC,\n    CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(col_data_parameters_version_number, '.', 2), '.', -1) AS UNSIGNED) ASC,\n    CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(col_data_parameters_version_number, '.', 3), '.', -1) AS UNSIGNED) ASC,\n    CAST(SUBSTRING_INDEX(col_data_parameters_version_number, '.', -1) AS UNSIGNED) ASC;\n"
    }
   ]
  }
 ]
}