{
 "title": "Old Versions",
 "description": "Data regarding users that are not using the latest release of Banana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Location DIstribution",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT col_data_locale_region AS \"lookup\", COUNT(*) FROM user_feedback.pd_old_version GROUP BY col_data_locale_region LIMIT 50 "
    }
   ]
  },
  {
   "title": "Languages",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT col_data_locale_language, COUNT(*) AS num_entries\nFROM user_feedback.pd_old_version\nGROUP BY col_data_locale_language\nORDER BY num_entries DESC;"
    }
   ]
  },
  {
   "title": "License Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT col_data_product_license AS \"License\", COUNT(*) FROM user_feedback.pd_old_version GROUP BY col_data_product_license LIMIT 50 "
    }
   ]
  },
  {
   "title": "Version Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "user_feedback",
     "rawSql": "SELECT col_data_platform_version, COUNT(col_data_platform_version) FROM user_feedback.pd_old_version GROUP BY col_data_platform_version ORDER BY col_data_platform_version ASC "
    }
   ]
  }
 ]
}