mysql -h localhost -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE USER IF NOT EXISTS '${GRAFANA_READER_USERNAME}'@'%' IDENTIFIED BY '${GRAFANA_READER_PASSWORD}';
GRANT SELECT ON ${MYSQL_DATABASE}.* TO '${GRAFANA_READER_USERNAME}'@'%';
EOF
