services:
  php-app:
    build: .
    ports:
      - "${HOST_PHP_PORT}:80"
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "${HOST_MYSQL_PORT}:${MYSQL_PORT}"
    env_file:
        - .env
    volumes:
        - db_data:/var/lib/mysql
        - ./mysql_entrypoint_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute='SELECT 1;'"]
      interval: 5s
      retries: 10


  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "${HOST_GRAFANA_PORT}:3000"
    env_file:
        - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  grafana_data:

