services:
  php-app:
    build: .
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - db
    env_file:
        - .env

  db:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
        - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

