services:
  php-app:
    build: .
    ports:
      - "1984:80"
    depends_on:
      - db
    env_file:
        - ./example.env

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
        - ./example.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

