services:
  php-app:
    build: .
    ports:
      - "${HOST_PHP_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
        - .env

  db:
    image: mysql:8.0
    ports:
      - "${HOST_MYSQL_PORT}:${MYSQL_PORT}"
    env_file:
        - .env
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute='SELECT 1;'"]
      interval: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

