services:
  php-app:
    build: .
    ports:
      - "${HOST_PHP_PORT}:80"
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "${HOST_MYSQL_PORT}:${MYSQL_PORT}"
    env_file:
        - .env
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute='SELECT 1;'"]
      interval: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
        - .env
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  grafana_data:

